#!/usr/bin/python

import os
import sys
from gecod import xmlrpc_frontend

root = '/usr/share/gecod'
if not os.path.exists(root+'/database.sqlite'):
    from gecod import database
    database.create('sqlite:///'+root+'/database.sqlite')

if not os.path.exists(root+'/certs/cert.pem'):
    curdir = os.getcwd()
    os.chdir(root+'/certs')
    os.popen('bash generate-pem.sh')
    os.chdir(curdir)

if os.getpid():
    print "Ejecutalo como root si tienes la base de datos con sqlite"

daemon = False
for i in sys.argv:
    if i == '-d':
        daemon = True

if daemon:
    pid = os.fork()
    if not pid:
        os.chdir('/')
        os.setsid()
        xmlrpc_frontend.main('/etc/gecod-xmlrpc.conf')
    else:
        try:
            open('/var/run/gecod-xmlrpc.pid', 'w').write(str(pid)+'\n')
        except:
            print "pid: ", pid

else:
    print "Para ejecutarlo como demonio usa la opcion -d"
    xmlrpc_frontend.main('/etc/gecod-xmlrpc.conf')

