#!/usr/bin/python

import getpass
import sys
from gecoc import gecolib

inp = raw_input
inp_p = getpass.getpass

server = inp("server: ")
user = inp("user: ")
passwd = inp_p("passwd: ")
print "----"
master1 = inp("actual master: ")
master2 = inp("new master: ")

gso = g.GSO(xmlrpc_server=server)
try:
    gso.auth(user, passwd)
except:
    print "wrong server, username or password"
    sys.exit(-1)

cont = inp("Continue? y/N")

if cont in 'yY':
    print "changing..."
    gso.change_master(master1, master2)
    print "changed"
else:
    print "not changed"
